### ISSUE TITLE
Packaging DAPodil

### ISSUE THREAD

**Issue by jw3** [jw3/example-daffodil-debug#21]
Add native packager and package a release of DAPodil.

Universal should be fine, and maybe a zip is better for portability.  Not sure how windows likes a tarball nowadays.

**Comment by arosien** [comment]
[Steve Lawrence commented](https://lists.apache.org/thread.html/r35d3d7715138d6ba40ec04d6ce00d0b52274536c182613f3e67c89f5%40%3Cdev.daffodil.apache.org%3E):

> I think a daffodil-dap module seems very reasonable. A benefit of
splitting this out is it could maybe be made an optional dependency so
it becomes easy to disable when in production if there are any
performance or security concerns with having debugging capabilities.
>
> Regarding churn, it might makes sense to create a "daffodil-dap" branch
that this work goes on, rather than merging directly to master. We did
this with the daffodil-runtime2 work and I think it worked out pretty
well. We still need to go through the same PR process to merge changes
into the branch, but it's much more acceptable for things to be in a not
fully working state or have known issues that need to be fixed that
wouldn't normally be merged into master. And then once things reach a
somewhat stable state, we can merge into the master branch and continue
development there.

... so I wonder about pushing there once this prototyping is at a good release stage. But also, does the current daffodil packaging work (potentially) with what we expect for the VS Code extension?

**Comment by arosien** [comment]
I believe this is implemented in the build file.
