### ISSUE TITLE
Relay data and infoset by event

### ISSUE THREAD

**Issue by Shanedell** [jw3/example-daffodil-debug#48]
@arosien Can we get the debugger to send custom events to the extension that relays the data position? Can we do this as well with the infoset?

Being able to receive the data position via custom events will be necessary for the html hex viewer of the extension to work fully. This would be the same for a similar view of what the infoset would look like at the current point in the debugging process.

Data position would be a greater priority than the infoset. 

We would also need to know the event name for both. For example the example htmlView from https://github.com/jw3/example-daffodil-vscode/issues/7#issuecomment-856877857 checks for `e.event == "displayHtml"`, so something like `displayDataPosition` or `displayInfoset` for the two different custom events would work.

**Comment by Shanedell** [comment]
Extension issues that this will help resolve:
- https://github.com/jw3/example-daffodil-vscode/issues/7
- https://github.com/jw3/example-daffodil-vscode/issues/35
- https://github.com/jw3/example-daffodil-vscode/issues/36
- https://github.com/jw3/example-daffodil-vscode/issues/45

**Comment by arosien** [comment]
If we want custom views, my assumption is that we _won't_ want to use the built-in `loadedSource` event which triggers vscode to load content updates via the `source` request (because it's likely difficult to customize the view that is used by default(?)). Luckily this is already controlled by the `supportsLoadedSourcesRequest` property of the `initialize` DAP response.

However, we can't use the launch parameters to specify if we want to choose between the custom and non-custom handling, because the `supportsLoadedSourcesRequest` capability is transmitted during the `initialize` response, which comes before the `launch` request.

Additionally, we could reuse the same `loadedSource` event handling (notification of changed source content) and `source` request from the extension itself. We would have to experiment to check:

* when the debugee responds `supportsLoadedSourcesRequest: false`, can the extension get notified of `loadedSource` events, and handle `source` requests and responses? (Perhaps VSCode doesn't allow capture of these, even if it doesn't expect them.)

I think this reuse should be a future option, and for the time being we add our own custom events.

**Comment by arosien** [comment]
@Shanedell @jw3 Proposal for data position event:

```typescript
interface DaffodilDataEvent extends Event {
  event: 'daffodil.data';

  /** Offset in bytes of the current position in the dataset.
  bytePos1b: number;
}
```

**Comment by arosien** [comment]
I think there can be additional fields in `DaffodilDataEvent` that describe the extent of the look ahead/behind window, i.e., the data that determines how the [range indicators of the "data dump"](https://github.com/apache/daffodil/blob/master/daffodil-runtime1/src/main/scala/org/apache/daffodil/processors/DataLoc.scala#L139) are positioned.

**Comment by arosien** [comment]
Proposal for infoset event:

```typescript
interface DaffodilInfosetEvent extends Event {
  event: 'daffodil.infoset';

  content: string;

  /** Default to returning the full infoset XML, but enable other encodings like diffs in the future. */
  mimeType: 'text/xml' | string;
}
```
